language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbshaw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbshaw/react-test npm test 

after_success:
  - docker build -t jbshaw/multi-client ./client
  - docker build -t jbshaw/multi-nginx ./nginx
  - docker build -t jbshaw/multi-server ./server
  - docker build -t jbshaw/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin   
     
  - docker push jbshaw/multi-client
  - docker push jbshaw/multi-nginx
  - docker push jbshaw/multi-server
  - docker push jbshaw/multi-worker





